### PR TITLE
[web-security] Validate PIN starts with a number for SQLi 1

### PR DESCRIPTION
**Pull request by sjzhu**
## What?
SQLi 1 has an unintended solve. Checking if the first character is a number should fix it while maintaining the intended solution.

@zardus

### CODE REVIEW

**Comment by zardus** [comment]
let's cut the number of lines by doing something like `if pin[0] in "0123456789":`. Just to keep the program small for people...

**Comment by sjzhu** [comment]
Tested in practice mode!

**Comment by sjzhu** [comment]
@zardus changes made and tested in practice mode!

**Comment by zardus** [comment]
Thanks!

**Pull request merged**
